name: rottexpr build - Ubuntu 64bit latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev

    - name: Build rottexpr
      working-directory: src
      run: make

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rott-ubuntu64-binary
        path: src/rott
