name: rottexpr build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev

    - name: Build rottexpr
      working-directory: src
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rottexpr-ubuntu64
        path: src/rott

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install sdl2 sdl2_mixer

    - name: Build rottexpr
      working-directory: src
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rottexpr-macos
        path: src/rott

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_mixer

    - name: Build rottexpr
      shell: msys {0}
      working-directory: src
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rottexpr-win64
        path: src/rott.exe
